#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

typedef struct {
    uint16_t tap;
    uint16_t hold;
    uint16_t held;
} tap_dance_tap_hold_t;

void tap_dance_tap_hold_finished(tap_dance_state_t *state, void *user_data) {
    tap_dance_tap_hold_t *tap_hold = (tap_dance_tap_hold_t *)user_data;

    if (state->pressed) {
        if (state->count == 1
#ifndef PERMISSIVE_HOLD
            && !state->interrupted
#endif
        ) {
            register_code16(tap_hold->hold);
            tap_hold->held = tap_hold->hold;
        } else {
            register_code16(tap_hold->tap);
            tap_hold->held = tap_hold->tap;
        }
    }
}

void tap_dance_tap_hold_reset(tap_dance_state_t *state, void *user_data) {
    tap_dance_tap_hold_t *tap_hold = (tap_dance_tap_hold_t *)user_data;

    if (tap_hold->held) {
        unregister_code16(tap_hold->held);
        tap_hold->held = 0;
    }
}

#define ACTION_TAP_DANCE_TAP_HOLD(tap, hold) \
    { .fn = {NULL, tap_dance_tap_hold_finished, tap_dance_tap_hold_reset}, .user_data = (void *)&((tap_dance_tap_hold_t){tap, hold, 0}), }

// Tap Dance declarations
enum {
  // a -> ä
  TD_E_AE,
  // w -> å
  TD_W_AA,
  // o -> ö
  TD_O_OE,
};

tap_dance_action_t tap_dance_actions[] = {
  [TD_E_AE] = ACTION_TAP_DANCE_TAP_HOLD(KC_E, RALT(KC_A)),
  [TD_W_AA] = ACTION_TAP_DANCE_TAP_HOLD(KC_W, RALT(KC_W)),
  [TD_O_OE] = ACTION_TAP_DANCE_TAP_HOLD(KC_O, RALT(KC_O))
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    tap_dance_action_t *action;

    switch (keycode) {
        case TD(TD_E_AE):
        case TD(TD_W_AA):
        case TD(TD_O_OE):
            action = &tap_dance_actions[QK_TAP_DANCE_GET_INDEX(keycode)];
            if (!record->event.pressed && action->state.count && !action->state.finished) {
                tap_dance_tap_hold_t *tap_hold = (tap_dance_tap_hold_t *)action->user_data;
                tap_code16(tap_hold->tap);
            }
    }
    return true;
}

// Combos

const uint16_t PROGMEM switcher[] = {LCTL_T(KC_F), RCTL_T(KC_J), COMBO_END};
const uint16_t PROGMEM launcher[] = {KC_G, KC_H, COMBO_END};
combo_t key_combos[] = {
    COMBO(switcher, LGUI(KC_H)),
    COMBO(launcher, LGUI(KC_G)), // keycodes with modifiers are possible too!
};



/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

// Aliases
#define XXXX KC_NO
#define ____ KC_TRNS

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        KC_Q, TD(TD_W_AA), TD(TD_E_AE), KC_R, KC_T,                                 KC_Y, KC_U, KC_I, TD(TD_O_OE), KC_P,
        LT(2, KC_A), LSFT_T(KC_S), LALT_T(KC_D), LCTL_T(KC_F), KC_G,                KC_H, RCTL_T(KC_J), LALT_T(KC_K), RSFT_T(KC_L), LT(2, KC_SCLN),
        KC_Z, KC_X, KC_C, KC_V, KC_B,                                               KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH,
        LT(3, KC_ESC), LGUI_T(KC_SPC),                                              LT(1, KC_BSPC), KC_ENT
    ),

    [1] = LAYOUT(
        XXXX,    XXXX,    XXXX,    XXXX,    XXXX,                                   XXXX,         XXXX,    XXXX,  XXXX,     XXXX,
        KC_HOME, KC_LCTL, KC_LEFT, KC_RGHT, KC_TAB,                                 LALT(KC_TAB), KC_DOWN, KC_UP, KC_RIGHT, KC_END,
        XXXX,    XXXX,    XXXX,    QK_REP,  XXXX,                                   XXXX,         XXXX,    XXXX,  XXXX,     XXXX,
                                ____, ____,                                         ____, ____
    ),

    [2] = LAYOUT(
        //  \             @         #            $          %                                 *            =          -           +           /
          KC_BSLS,      KC_AT,    KC_HASH,     KC_DLR,    KC_PERC,                          KC_ASTR,     KC_EQL,    KC_MINS,    KC_PLUS,    KC_SLSH,
        //  [             ]         (            )          '                                 "            {          }           :           ;
          KC_LBRC,      KC_RBRC,  KC_LPRN,     KC_RPRN,   KC_QUOT,                          KC_DQUO,     KC_LCBR,   KC_RCBR,    KC_COLN,    KC_SCLN,
        //  <             >         |            &          ^                                 !            ?          ,           .           _
          KC_LT,        KC_GT,    KC_PIPE,     KC_AMPR,   KC_CIRC,                          KC_EXLM,     KC_QUES,   KC_COMM,    KC_DOT,     KC_UNDS,
        //                                       ~                                                         `
                                               KC_TILD,   KC_TAB,                      LALT(KC_TAB),     KC_GRV
    ),
    [3] = LAYOUT(
        KC_F1, KC_F2, KC_F3, KC_F4, KC_5,                                                 KC_F6,   KC_F7, KC_F8, KC_F9, KC_F10,
        KC_1,  KC_2,  KC_3,  KC_4,  KC_5,                                                 KC_6,    KC_7,  KC_8,  KC_9,  KC_0,
        XXXX,  XXXX,  XXXX,  XXXX,  XXXX,                                                 XXXX,    XXXX,  XXXX,  XXXX,  XXXX,
                                    ____, ____,                                    ____,  ____
    )
};

#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C


