#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

#include "../../td.c"

// This code comes from https://docs.qmk.fm/features/caps_word#configure-which-keys-are-word-breaking
// but it is modified to work better with tap/dance actions, which would normally cancel
// the caps word, which is not something we want. So instead of the default being to
// return false for key codes not defined here, we will return true by default and only
// return false on certain (explicit) exceptions.
bool caps_word_press_user(uint16_t keycode) {
    switch (keycode) {
        // Keycodes that continue Caps Word, with shift applied.
        case KC_A ... KC_Z:
        case TD(TD_E_AE):
        case TD(TD_W_AA):
        case TD(TD_O_OE):
        case KC_MINS:
            add_weak_mods(MOD_BIT(KC_LSFT));  // Apply shift to next key.
            return true;

        // Keycodes that deactivates Caps Word
        case KC_SPC:
        case KC_ENT:
        case KC_TAB:
        case KC_COMM:
        case KC_DOT:
        case KC_ESC:
        case KC_BSLS:
        case KC_AT:
        case KC_HASH:
        case KC_DLR:
        case KC_PERC:
        case KC_ASTR:
        case KC_EQL:
        case KC_PLUS:
        case KC_SLSH:
        case KC_LBRC:
        case KC_RBRC:
        case KC_LPRN:
        case KC_RPRN:
        case KC_QUOT:
        case KC_DQUO:
        case KC_LCBR:
        case KC_RCBR:
        case KC_COLN:
        case KC_SCLN:
        case KC_LT:
        case KC_GT:
        case KC_PIPE:
        case KC_AMPR:
        case KC_CIRC:
        case KC_EXLM:
        case KC_QUES:
        case KC_TILD:
        case KC_GRV:
            return false;  // Deactivate Caps Word.

        // By default, all other keycodes will keep continue caps word enabled, but
        // will not be shifted for the given key
        default:
            return true;
    }
}

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

// Aliases
#define XXXX KC_NO
#define ____ KC_TRNS

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5,                                                    KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS,
        XXXX, KC_Q, TD(TD_W_AA), TD(TD_E_AE), KC_R, KC_T,                                        KC_Y, KC_U, KC_I, TD(TD_O_OE), KC_P, XXXX,
        KC_ESC, LT(2, KC_A), LSFT_T(KC_S), LALT_T(KC_D), LCTL_T(KC_F), KC_G,                     KC_H, RCTL_T(KC_J), LALT_T(KC_K), RSFT_T(KC_L), LT(2, KC_SCLN), KC_ENT,
        KC_TAB, KC_Z, KC_X, KC_C, KC_V, KC_B, MEH(KC_LEFT),                        MEH(KC_RGHT), KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, LALT(KC_TAB),
        CW_TOGG, KC_LALT, LT(3, KC_ESC), LGUI_T(KC_SPC),                           LT(1, KC_BSPC), TD(TD_ENTER), KC_RALT, KC_DEL
    ),

    [1] = LAYOUT(
        XXXX,     XXXX,     XXXX,     XXXX,     XXXX,            XXXX,                                   XXXX,    XXXX,    XXXX,      XXXX,     XXXX,   XXXX,
        XXXX,     XXXX,     XXXX,     XXXX,     XXXX,            XXXX,                                   XXXX,    XXXX,   TG(1),      XXXX,     XXXX,   XXXX,
        XXXX,     XXXX,  KC_LCTL,  KC_LEFT,  KC_RGHT,            XXXX,                                KC_HOME, KC_DOWN,   KC_UP,    KC_END,     XXXX,   XXXX,
        XXXX,     XXXX,     XXXX,     XXXX,   QK_REP,            XXXX,   XXXX,                  XXXX,    XXXX,    XXXX,    XXXX,      XXXX,     XXXX,   XXXX,
                            ____,     ____,    TG(1),            ____,                                   ____,    ____,    ____,      ____
    ),

    // Tap dance so ( on normal press and ) on hold and () on double tap, and the same for {}, [] and <>?
    [2] = LAYOUT(
        ____, RALT(KC_1), RALT(KC_2), RALT(KC_3), RALT(KC_4), RALT(KC_5),                       RALT(KC_6), RALT(KC_7), RALT(KC_8), RALT(KC_9), RALT(KC_0), ____,
        //                               @                 #               $             %                                 *            =          +                  
        ____,    XXXX,                 KC_AT,            KC_HASH,        KC_DLR,       KC_PERC,                          KC_ASTR,     KC_EQL,    KC_PLUS,    XXXX,          XXXX,  ____,
        //            []                < >               { }             ( )            '                                 "            -          _           :           ;
        ____,    TD(TD_BRACKET),    TD(TD_ANGLE),     TD(TD_CURLY),   TD(TD_PAREN),    KC_QUOT,                          KC_DQUO,     KC_MINS,   KC_UNDS,    KC_COLN,    KC_SCLN, ____,
        //         \                                       |                &             ^                                 !            ?          ,           .           /
        ____,    KC_BSLS,             XXXX,              KC_PIPE,         KC_AMPR,      KC_CIRC, XXXX,              XXXX, KC_EXLM,     KC_QUES,   KC_COMM,    KC_DOT,     KC_SLSH, ____,
        //                                                ~                                                          `
                                   ____,       ____,    KC_TILD,     KC_TAB,                     LALT(KC_TAB),     KC_GRV,       ____,       ____
    ),

    [3] = LAYOUT(
        XXXX, XXXX,  XXXX,  XXXX,  XXXX,  QK_BOOT,                                              QK_BOOT, XXXX,  XXXX,  XXXX,  XXXX,   KC_PSCR,
        XXXX, KC_F1, KC_F2, KC_F3, KC_F4, KC_5,                                                 KC_F6,   KC_F7, KC_F8, KC_F9, KC_F10, KC_F11,
        XXXX, KC_1,  KC_2,  KC_3,  KC_4,  KC_5,                                                 KC_6,    KC_7,  KC_8,  KC_9,  KC_0,   XXXX,
        XXXX, XXXX,  XXXX,  XXXX,  XXXX,  XXXX, LCTL(KC_PMNS),                   LCTL(KC_PPLS), XXXX,    XXXX,  XXXX,  XXXX,  XXXX,   XXXX,
                            ____,  ____,  ____, ____,                                  ____,  ____,    ____,  ____
    ),

// Layer template, copy paste as needed
//    [4] = LAYOUT(
//        XXXX, XXXX,  XXXX,  XXXX,  XXXX,  XXXX,                                                 XXXX,    XXXX,  XXXX,  XXXX,  XXXX,   XXXX,
//        XXXX, XXXX,  XXXX,  XXXX,  XXXX,  XXXX,                                                 XXXX,    XXXX,  XXXX,  XXXX,  XXXX,   XXXX,
//        XXXX, XXXX,  XXXX,  XXXX,  XXXX,  XXXX,                                                 XXXX,    XXXX,  XXXX,  XXXX,  XXXX,   XXXX,
//        XXXX, XXXX,  XXXX,  XXXX,  XXXX,  XXXX,  ____,                                    ____, XXXX,    XXXX,  XXXX,  XXXX,  XXXX,   XXXX,
//                            ____,  ____,  ____,  ____,                                    ____, ____,    ____,  ____
//    ),

};

// Combos
const uint16_t PROGMEM switcher[] = {LCTL_T(KC_F), RCTL_T(KC_J), COMBO_END};
const uint16_t PROGMEM launcher[] = {KC_G, KC_H, COMBO_END};
const uint16_t PROGMEM nav_lock[] = {LGUI_T(KC_SPC), LT(1, KC_BSPC), COMBO_END};
const uint16_t PROGMEM caps_word[] = {LSFT_T(KC_S), RSFT_T(KC_L), COMBO_END};

combo_t key_combos[] = {
    COMBO(switcher, LGUI(KC_H)),
    COMBO(launcher, LGUI(KC_G)), // keycodes with modifiers are possible too!
    COMBO(nav_lock, TG(1)),
    COMBO(caps_word, QK_CAPS_WORD_TOGGLE)
};

#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C


