#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

typedef struct {
    uint16_t tap;
    uint16_t hold;
    uint16_t held;
} tap_dance_tap_hold_t;

void tap_dance_tap_hold_finished(tap_dance_state_t *state, void *user_data) {
    tap_dance_tap_hold_t *tap_hold = (tap_dance_tap_hold_t *)user_data;

    if (state->pressed) {
        if (state->count == 1
#ifndef PERMISSIVE_HOLD
            && !state->interrupted
#endif
        ) {
            register_code16(tap_hold->hold);
            tap_hold->held = tap_hold->hold;
        } else {
            register_code16(tap_hold->tap);
            tap_hold->held = tap_hold->tap;
        }
    }
}

void tap_dance_tap_hold_reset(tap_dance_state_t *state, void *user_data) {
    tap_dance_tap_hold_t *tap_hold = (tap_dance_tap_hold_t *)user_data;

    if (tap_hold->held) {
        unregister_code16(tap_hold->held);
        tap_hold->held = 0;
    }
}

#define ACTION_TAP_DANCE_TAP_HOLD(tap, hold) \
    { .fn = {NULL, tap_dance_tap_hold_finished, tap_dance_tap_hold_reset}, .user_data = (void *)&((tap_dance_tap_hold_t){tap, hold, 0}), }

// Tap Dance declarations
enum {
  // a -> ä
  TD_E_AE,
  // w -> å
  TD_W_AA,
  // o -> ö
  TD_O_OE,
};

tap_dance_action_t tap_dance_actions[] = {
  [TD_E_AE] = ACTION_TAP_DANCE_TAP_HOLD(KC_E, RALT(KC_A)),
  [TD_W_AA] = ACTION_TAP_DANCE_TAP_HOLD(KC_W, RALT(KC_W)),
  [TD_O_OE] = ACTION_TAP_DANCE_TAP_HOLD(KC_O, RALT(KC_O))
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    tap_dance_action_t *action;

    switch (keycode) {
        case TD(TD_E_AE):
        case TD(TD_W_AA):
        case TD(TD_O_OE):
            action = &tap_dance_actions[QK_TAP_DANCE_GET_INDEX(keycode)];
            if (!record->event.pressed && action->state.count && !action->state.finished) {
                tap_dance_tap_hold_t *tap_hold = (tap_dance_tap_hold_t *)action->user_data;
                tap_code16(tap_hold->tap);
            }
    }
    return true;
}

// Combos

const uint16_t PROGMEM switcher[] = {KC_F, KC_J, COMBO_END};
const uint16_t PROGMEM launcher[] = {KC_G, KC_H, COMBO_END};
combo_t key_combos[] = {
    COMBO(switcher, LGUI(KC_H)),
    COMBO(launcher, LGUI(KC_G)), // keycodes with modifiers are possible too!
};



/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

// Aliases
#define XXXX KC_NO
#define ____ KC_TRNS

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5,                                                    KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS,
        XXXX, KC_Q, TD(TD_W_AA), TD(TD_E_AE), KC_R, KC_T,                                        KC_Y, KC_U, KC_I, TD(TD_O_OE), KC_P, KC_EQL,
        KC_ESC, LCTL_T(KC_A), KC_S, KC_D, KC_F, KC_G,                                            KC_H, KC_J, KC_K, KC_L, RCTL_T(KC_SCLN), KC_QUOT,
        KC_TAB, KC_Z, KC_X, KC_C, KC_V, KC_B, MEH(KC_LEFT),                                      MEH(KC_RGHT), KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, LALT(KC_TAB),
        CW_TOGG, KC_LALT, OSM(MOD_LSFT), LGUI_T(KC_SPC),                                         LT(1,KC_BSPC), LT(2,KC_ENT), KC_RALT, KC_DEL
    ),
    [1] = LAYOUT(XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, LCTL(KC_LEFT), LCTL(KC_RGHT), XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, KC_HOME, KC_LEFT, KC_RGHT, KC_END, KC_PGDN, KC_DOWN, KC_UP, KC_PGUP, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, QK_REP, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, ____, ____, XXXX, XXXX, XXXX),
    [2] = LAYOUT(
        ____, RALT(KC_1), RALT(KC_2), RALT(KC_3), RALT(KC_4), RALT(KC_5),                       RALT(KC_6), RALT(KC_7), RALT(KC_8), RALT(KC_9), RALT(KC_0), ____,
        ____, LSFT(KC_1), LSFT(KC_2), LSFT(KC_3), LSFT(KC_4), LSFT(KC_5),                       LSFT(KC_6), LSFT(KC_7), LSFT(KC_8), LSFT(KC_9), LSFT(KC_0), ____,
        ____, KC_LT, KC_LBRC, KC_LCBR, KC_LPRN, KC_DQUO,                                        KC_QUOT, KC_RPRN, KC_RCBR, KC_RBRC, KC_GT, ____,
        ____, KC_PIPE, XXXX, XXXX, XXXX, XXXX, XXXX,                                               XXXX, XXXX, XXXX, ____, ____, ____, ____,
        ____, ____, ____, ____,                                                                 ____, ____, ____, ____
    ),
    [3] = LAYOUT(QK_BOOT, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, QK_BOOT, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, LCTL(KC_PMNS), LSFT(KC_PPLS), XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, XXXX, ____, ____, XXXX, XXXX, XXXX)
};

#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C


